build:code:
  stage: build
  image: maven:3-alpine
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  artifacts:
    paths:
      - target/
  cache:
    paths:
      - .m2/repository/
      - target/
  script:
    - echo "Asia/Shanghai" > /etc/timezone
    - mvn clean deploy -DskipTests
test:image:
  stage: test
  image: docker
  cache:
    paths:
      - .m2/repository/
      - target/
  dependencies:
    - :build:code
  script:
    - chmod 777 build-docker.sh && dos2unix build-docker.sh && source build-docker.sh